import dog from "../../Assets/category-dog.png";
import cat from "../../Assets/category-cat.png";

const animals = [
  {
    id: 1,
    animalType: "dog",
    name: "Buddy",
    image: dog,
    breed: "Golden Retriever",
    age: "2 years",
    sex: "Male",
    address: "123 Main St, City",
    health: "Vaccinated and healthy",
    adoptionFee: "$200",
    moreInformation: "Friendly and loves playing fetch.",
    ownerWhatsApp: "+1 123-456-7890",
    email: "buddy@example.com",
  },
  {
    id: 2,
    animalType: "dog",
    name: "Bwrgf3ruddy",
    image: dog,
    breed: "Golden Retriever",
    age: "2 years",
    sex: "Male",
    address: "123 Main St, City",
    health: "Vaccinated and healthy",
    adoptionFee: "$200",
    moreInformation: "Friendly and loves playing fetch.",
    ownerWhatsApp: "+1 123-456-7890",
    email: "buddy@example.com",
  },
  {
    id: 3,
    animalType: "dog",
    name: "Max",
    image: dog,
    breed: "Labrador Retriever",
    age: "3 years",
    sex: "Male",
    address: "456 Elm St, City",
    health: "Neutered and vaccinated",
    adoptionFee: "$250",
    moreInformation: "Energetic and enjoys outdoor activities.",
    ownerWhatsApp: "+1 987-654-3210",
    email: "max@example.com",
  },
  {
    id: 4,
    animalType: "dog",
    name: "Max",
    image: dog,
    breed: "Labrador Retriever",
    age: "3 years",
    sex: "Male",
    address: "456 Elm St, City",
    health: "Neutered and vaccinated",
    adoptionFee: "$250",
    moreInformation: "Energetic and enjoys outdoor activities.",
    ownerWhatsApp: "+1 987-654-3210",
    email: "max@example.com",
  },
  {
    id: 1,
    animalType: "dog",
    name: "Max",
    image: dog,
    breed: "Labrador Retriever",
    age: "3 years",
    sex: "Male",
    address: "456 Elm St, City",
    health: "Neutered and vaccinated",
    adoptionFee: "$250",
    moreInformation: "Energetic and enjoys outdoor activities.",
    ownerWhatsApp: "+1 987-654-3210",
    email: "max@example.com",
  },
  {
    id: 1,
    animalType: "cat",
    name: "Whiskers",
    image: cat,
    breed: "Siamese",
    age: "1 year",
    sex: "Female",
    address: "789 Oak St, City",
    health: "Spayed and vaccinated",
    adoptionFee: "$150",
    moreInformation: "Playful and enjoys cuddling.",
    ownerWhatsApp: "+1 123-456-7890",
    email: "whiskers@example.com",
  },
  {
    id: 2,
    animalType: "cat",
    name: "coco",
    image: cat,
    breed: "Siamese",
    age: "9 months",
    sex: "Female",
    address: "789 Oak St, City",
    health: "Spayed and vaccinated",
    adoptionFee: "$150",
    moreInformation: "Playful and enjoys cuddling.",
    ownerWhatsApp: "+1 123-456-7890",
    email: "whiskers@example.com",
  },
  {
    id: 3,
    animalType: "cat",
    name: "Oscar",
    image: cat,
    breed: "Maine Coon",
    age: "2 years",
    sex: "Male",
    address: "987 Pine St, City",
    health: "Vaccinated and healthy",
    adoptionFee: "$180",
    moreInformation: "Laid-back and loves lounging around.",
    ownerWhatsApp: "+1 987-654-3210",
    email: "oscar@example.com",
  },
];

export default animals;
